services:
  # PostgreSQL database
  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data_mlflow_server:/var/lib/postgresql/data
    healthcheck:
      test: bash -c 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tpp-network

  # MinIO server
  minio:
    image: minio/minio
    expose:
      - "${MINIO_API_PORT}"
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      # MinIO Console is available at http://localhost:${MINIO_CONSOLE_PORT}
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/${MINIO_API_PORT}' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    networks:
      - tpp-network
  # Create a bucket named "bucket" if it doesn't exist
  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:${MINIO_API_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      if ! mc ls minio/bucket; then
        mc mb minio/bucket
      else
        echo 'bucket already exists'
      fi
      "
    networks:
      - tpp-network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:${MLFLOW_SERVER_PORT}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:${MINIO_API_PORT}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_SERVER_ALLOWED_HOSTS=*
    ports:
      - "${MLFLOW_SERVER_PORT}:${MLFLOW_SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: >
      server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      --default-artifact-root s3://bucket/artifacts
      --host 0.0.0.0
      --port ${MLFLOW_SERVER_PORT}
    networks:
      - tpp-network

volumes:
  postgres_data_mlflow_server:

networks:
  tpp-network:
    external: true
