services:
  mlflow-logger:
    build:
      context: .
      dockerfile: Dockerfile.logger
    env_file:
      - .env
    networks:
      - tpp-network
    depends_on:
      sessions-db:
        condition: service_healthy

  sessions-db:
    container_name: sessions-db
    image: postgres:15
    environment:
      - POSTGRES_USER=${MLFLOW_LOGGER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MLFLOW_LOGGER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${MLFLOW_LOGGER_POSTGRES_DB}
    ports:
      - ${MLFLOW_LOGGER_POSTGRES_PORT}:5432
    volumes:
      - postgres_data_mlflow_logger:/var/lib/postgresql/data
    healthcheck:
      test: bash -c 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tpp-network

volumes:
  postgres_data_mlflow_logger:

networks:
  tpp-network:
    external: true
